// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int count = Integer.parseInt(args[0]);
	    double random;
	    int moreThanHalf = 0, lessThanHalf;
	    for(int i = 0; i < count; i++)
	    {
	        random = Math.random();
            if(random > 0.5)
            {
                moreThanHalf++;
            }
	    }
	    lessThanHalf = count - moreThanHalf;
	    System.out.println("> 0.5: " + moreThanHalf + " times");
	    System.out.println("<= 0.5: " + lessThanHalf + " times");
	}
}
